# Generated by Django 4.2.1 on 2023-05-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hnmapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuthToken",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "admin_auth_tokens",
            },
        ),
        migrations.DeleteModel(
            name="UserGroups",
        ),
    ]
